#!/bin/sh
cd tests

rm -rf tests.log

echo nameserver 8.8.4.4 >> /etc/resolv.conf

# known good tests
MQTT_TESTS="\
mqtt_connection_publish_QoS1_timeout  \
mqtt_connection_unsub_timeout  \
mqtt_connection_publish_QoS1_timeout_connection_lost_reset_time  \
mqtt_connect_disconnect  \
mqtt_connect_set_will_login  \
mqtt_connection_interrupted  \
mqtt_connection_any_publish  \
mqtt_connection_timeout  \
mqtt_connection_connack_timeout  \
mqtt_connect_subscribe  \
mqtt_connect_subscribe_fail_from_broker  \
mqtt_connect_subscribe_multi  \
mqtt_connect_unsubscribe  \
mqtt_connect_resubscribe  \
mqtt_connect_publish  \
mqtt_connect_publish_payload  \
mqtt_connection_offline_publish  \
mqtt_connection_disconnect_while_reconnecting  \
mqtt_connection_closes_while_making_requests  \
mqtt_connection_resend_packets  \
mqtt_connection_consistent_retry_policy  \
mqtt_connection_not_resend_packets_on_healthy_connection  \
mqtt_connection_destory_pending_requests  \
mqtt_clean_session_not_retry  \
mqtt_clean_session_discard_previous  \
mqtt_clean_session_keep_next_session  \	
"

for TEST in $MQTT_TESTS
do
./aws-c-mqtt-tests $TEST >> tests.log
done

sed  -e '/OK/ s/^/PASS: / ; /FAILED/ s/^/FAIL: / ; /ERROR/ s/^/FAIL: /' tests.log

### disabled tests - when doing ptest in codebuild ptest hangs - try to reduce tests - those all do pass locally ###
